### ISSUE TITLE
Compile policies with concrete keys

### ISSUE THREAD

**Issue by amanzag** [bitcoinerlab/miniscript#4]
I'm looking to use this library to build relatively complex bitcoin scripts that I can include in my transactions, but it seems that it only works with with key placeholders and not with actual keys.

For instance, this works:
`pk(A)`
But this doesn't:
`pk(02e96fe52ef0e22d2f131dd425ce1893073a3c6ad20e8cac36726393dfb4856a4c)`

Is there a way to is real keys? If there is, it isn't documented.

**Comment by landabaso** [comment]
Apologies for the delayed response! At present, the library is designed to work with key placeholders rather than actual keys. However, I am planning a significant refactor of this library which will move away from C++ transpilation. The process of converting miniscript to Bitcoin Script is relatively straightforward, and I'm confident that the upcoming changes will support the use of real keys.

In the meantime, I recommend using generic keys with the library and then replacing them with actual keys in your final script. This should serve as an effective workaround until the update is rolled out. Thank you for your patience and for using the library!
